package com.rfizzle.meridian.enchanting;

import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.enchantment.EnchantmentInstance;

import java.util.List;

/**
 * API interface that items can implement to customize the enchantment selection at the
 * enchanting table. The selection algorithm in {@link RealEnchantmentHelper#selectEnchantment}
 * checks for this interface after building the enchantment list and calls
 * {@link #selectEnchantments} to allow post-processing.
 *
 * <p>Implementations must be deterministic with respect to the random seed — the same seed
 * must produce the same result every time.
 */
public interface EnchantableItem {

    /**
     * Post-processes the enchantment list selected by the enchanting table.
     *
     * @param builtList the enchantment list as generated by the selection algorithm
     * @param rand      pre-seeded random; consume deterministically
     * @param stack     the stack being enchanted (not yet enchanted)
     * @param level     the slot's enchanting power level
     * @param stats     aggregated table stats
     * @return the final enchantment list; by default returns {@code builtList} unchanged
     */
    default List<EnchantmentInstance> selectEnchantments(
            List<EnchantmentInstance> builtList,
            RandomSource rand,
            ItemStack stack,
            int level,
            StatCollection stats
    ) {
        return builtList;
    }
}
