package com.rfizzle.meridian.data;

import com.rfizzle.meridian.Meridian;
import com.rfizzle.meridian.shelf.MeridianShelves;

import java.util.LinkedHashMap;
import java.util.Map;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TextureMapping;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

/**
 * Generates blockstates and parented block models for every shelf in {@link MeridianShelves}.
 *
 * <p>Each shelf renders as a {@code cube_column}: a unique side texture plus an end (top/bottom)
 * texture. The end is either a custom Meridian top (e.g. {@code prismarine_shelf_top},
 * {@code sculkshelf_top}) or a vanilla material block, where the shelf reads as built from that
 * material.
 *
 * <p>Item models for each shelf are auto-generated by {@link FabricModelProvider}'s parent
 * pipeline because every shelf is registered as a {@code BlockItem}; the auto-generated item
 * model parents the block model.
 *
 * <p>Standalone item models for {@code infused_breath}, {@code warden_tendril},
 * {@code prismatic_web}, and the three tomes ship via {@link #generateItemModels} as those
 * items are introduced in Epics 4 and 5 — the slot is reserved here so adding them is a
 * single-line change.
 */
public class MeridianModelProvider extends FabricModelProvider {

    private static final ResourceLocation HONEYCOMB_SHELF_TOP = fizzleBlock("honeycomb_shelf_top");
    private static final ResourceLocation MELON_SHELF_TOP = fizzleBlock("melon_shelf_top");
    private static final ResourceLocation STONE_SHELF_TOP = fizzleBlock("stone_shelf_top");
    private static final ResourceLocation PRISMARINE_BRICKS = vanillaBlock("prismarine_bricks");
    private static final ResourceLocation PURPUR_BLOCK = vanillaBlock("purpur_block");
    private static final ResourceLocation PRISMARINE_SHELF_TOP = fizzleBlock("prismarine_shelf_top");
    private static final ResourceLocation NETHER_BRICK_SHELF_TOP = fizzleBlock("nether_brick_shelf_top");
    private static final ResourceLocation DEEPSLATE_SHELF_TOP = fizzleBlock("deepslate_shelf_top");
    private static final ResourceLocation END_STONE_SHELF_TOP = fizzleBlock("end_stone_shelf_top");

    public MeridianModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators gens) {
        Map<Block, ColumnTextures> shelves = shelfTextures();
        for (Map.Entry<Block, ColumnTextures> entry : shelves.entrySet()) {
            Block block = entry.getKey();
            ColumnTextures tex = entry.getValue();
            TextureMapping mapping = TextureMapping.column(tex.side(), tex.end());
            ResourceLocation modelId = ModelTemplates.CUBE_COLUMN.create(block, mapping, gens.modelOutput);
            gens.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, modelId));
        }
    }

    @Override
    public void generateItemModels(ItemModelGenerators gens) {
    }

    /**
     * Returns the side+end texture pair used by every shelf. The map preserves registration order
     * so generated output diffs stay deterministic. Visible for tests.
     */
    public static Map<Block, ColumnTextures> shelfTextures() {
        Map<Block, ColumnTextures> map = new LinkedHashMap<>();
        // Wood tier — original Meridian shelves, custom tops
        map.put(MeridianShelves.BEESHELF, column("beeshelf", HONEYCOMB_SHELF_TOP));
        map.put(MeridianShelves.MELONSHELF, column("melonshelf", MELON_SHELF_TOP));
        // Stone tier — baseline
        map.put(MeridianShelves.STONESHELF, column("stoneshelf", STONE_SHELF_TOP));
        // Nether — original Meridian nether-brick shelf, custom top
        map.put(MeridianShelves.HELLSHELF, column("hellshelf", NETHER_BRICK_SHELF_TOP));
        map.put(MeridianShelves.BLAZING_HELLSHELF, column("blazing_hellshelf", NETHER_BRICK_SHELF_TOP));
        map.put(MeridianShelves.GLOWING_HELLSHELF, column("glowing_hellshelf", NETHER_BRICK_SHELF_TOP));
        map.put(MeridianShelves.INFUSED_HELLSHELF, column("infused_hellshelf", NETHER_BRICK_SHELF_TOP));
        // Ocean — original Meridian prismarine shelf, custom top
        map.put(MeridianShelves.SEASHELF, column("seashelf", PRISMARINE_SHELF_TOP));
        map.put(MeridianShelves.HEART_SEASHELF, column("heart_seashelf", PRISMARINE_SHELF_TOP));
        map.put(MeridianShelves.CRYSTAL_SEASHELF, column("crystal_seashelf", PRISMARINE_SHELF_TOP));
        map.put(MeridianShelves.INFUSED_SEASHELF, column("infused_seashelf", PRISMARINE_SHELF_TOP));
        // End — original Meridian end-stone shelf, custom top
        map.put(MeridianShelves.ENDSHELF, column("endshelf", END_STONE_SHELF_TOP));
        map.put(MeridianShelves.PEARL_ENDSHELF, column("pearl_endshelf", END_STONE_SHELF_TOP));
        map.put(MeridianShelves.DRACONIC_ENDSHELF, column("draconic_endshelf", END_STONE_SHELF_TOP));
        // Deepslate — original Meridian deepslate shelf, custom top
        map.put(MeridianShelves.DEEPSHELF, column("deepshelf", DEEPSLATE_SHELF_TOP));
        map.put(MeridianShelves.DORMANT_DEEPSHELF, column("dormant_deepshelf", DEEPSLATE_SHELF_TOP));
        map.put(MeridianShelves.ECHOING_DEEPSHELF, column("echoing_deepshelf", DEEPSLATE_SHELF_TOP));
        map.put(MeridianShelves.SOUL_TOUCHED_DEEPSHELF, column("soul_touched_deepshelf", DEEPSLATE_SHELF_TOP));
        // Sculk-tier (reanimated bookshelf subtype, shared end texture)
        map.put(MeridianShelves.ECHOING_SCULKSHELF, column("echoing_sculkshelf", fizzleBlock("sculkshelf_top")));
        map.put(MeridianShelves.SOUL_TOUCHED_SCULKSHELF, column("soul_touched_sculkshelf", fizzleBlock("sculkshelf_top")));
        // Utility — clue shelves
        map.put(MeridianShelves.SIGHTSHELF, column(fizzleBlock("sight_side"), fizzleBlock("sight_top")));
        map.put(MeridianShelves.SIGHTSHELF_T2, column("sightshelf_t2", fizzleBlock("sightshelf_t2_top")));
        // Utility — rectification shelves
        map.put(MeridianShelves.RECTIFIER, column("rectifier", PRISMARINE_BRICKS));
        map.put(MeridianShelves.RECTIFIER_T2, column("rectifier_t2", fizzleBlock("rectifier_t2_top")));
        map.put(MeridianShelves.RECTIFIER_T3, column("rectifier_t3", PURPUR_BLOCK));
        return map;
    }

    private static ColumnTextures column(String sideName, ResourceLocation end) {
        return column(fizzleBlock(sideName), end);
    }

    private static ColumnTextures column(ResourceLocation side, ResourceLocation end) {
        return new ColumnTextures(side, end);
    }

    private static ResourceLocation fizzleBlock(String name) {
        return Meridian.id("block/" + name);
    }

    private static ResourceLocation vanillaBlock(String name) {
        return ResourceLocation.withDefaultNamespace("block/" + name);
    }

    /** Side+end texture pair for a {@code cube_column} shelf model. */
    public record ColumnTextures(ResourceLocation side, ResourceLocation end) {
    }
}
