package com.rfizzle.meridian.data;

import com.rfizzle.meridian.Meridian;
import com.rfizzle.meridian.shelf.MeridianShelves;

import java.util.LinkedHashMap;
import java.util.Map;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TextureMapping;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

/**
 * Generates blockstates and parented block models for every shelf in {@link MeridianShelves}.
 *
 * <p>Each shelf renders as a {@code cube_column} with a side texture (the unique shelf face) and
 * an end texture (the tier-themed top/bottom). Sources are 1:1 with Zenith's shelf models — see
 * {@code /home/rfizzle/Projects/Zenith/src/main/resources/assets/zenith/models/block/} for the
 * originals. Three Zenith blocks ({@code infused_hellshelf}, {@code infused_seashelf},
 * {@code dormant_deepshelf}) lack a unique side texture and fall back to their family's base
 * shelf side, matching Zenith's blockstate aliasing.
 *
 * <p>Item models for each shelf are auto-generated by {@link FabricModelProvider}'s parent
 * pipeline because every shelf is registered as a {@code BlockItem}; the auto-generated item
 * model parents the block model.
 *
 * <p>Standalone item models for {@code infused_breath}, {@code warden_tendril},
 * {@code prismatic_web}, and the three tomes ship via {@link #generateItemModels} as those
 * items are introduced in Epics 4 and 5 — the slot is reserved here so adding them is a
 * single-line change.
 */
public class MeridianModelProvider extends FabricModelProvider {

    private static final ResourceLocation BEEHIVE_END = vanillaBlock("beehive_end");
    private static final ResourceLocation MELON_TOP = vanillaBlock("melon_top");
    private static final ResourceLocation POLISHED_ANDESITE = vanillaBlock("polished_andesite");
    private static final ResourceLocation NETHER_BRICKS = vanillaBlock("nether_bricks");
    private static final ResourceLocation PRISMARINE_BRICKS = vanillaBlock("prismarine_bricks");
    private static final ResourceLocation END_STONE_BRICKS = vanillaBlock("end_stone_bricks");
    private static final ResourceLocation CRACKED_DEEPSLATE_TILES = vanillaBlock("cracked_deepslate_tiles");
    private static final ResourceLocation PURPUR_BLOCK = vanillaBlock("purpur_block");

    public MeridianModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators gens) {
        Map<Block, ColumnTextures> shelves = shelfTextures();
        for (Map.Entry<Block, ColumnTextures> entry : shelves.entrySet()) {
            Block block = entry.getKey();
            ColumnTextures tex = entry.getValue();
            TextureMapping mapping = TextureMapping.column(tex.side(), tex.end());
            ResourceLocation modelId = ModelTemplates.CUBE_COLUMN.create(block, mapping, gens.modelOutput);
            gens.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, modelId));
        }
    }

    @Override
    public void generateItemModels(ItemModelGenerators gens) {
    }

    /**
     * Returns the side+end texture pair used by every shelf. The map preserves registration order
     * so generated output diffs stay deterministic. Visible for tests.
     */
    public static Map<Block, ColumnTextures> shelfTextures() {
        Map<Block, ColumnTextures> map = new LinkedHashMap<>();
        // Wood tier — vanilla organic ends
        map.put(MeridianShelves.BEESHELF, column("beeshelf", BEEHIVE_END));
        map.put(MeridianShelves.MELONSHELF, column("melonshelf", MELON_TOP));
        // Stone tier — baseline
        map.put(MeridianShelves.STONESHELF, column("stoneshelf", POLISHED_ANDESITE));
        // Nether
        map.put(MeridianShelves.HELLSHELF, column("hellshelf", NETHER_BRICKS));
        map.put(MeridianShelves.BLAZING_HELLSHELF, column("blazing_hellshelf", NETHER_BRICKS));
        map.put(MeridianShelves.GLOWING_HELLSHELF, column("glowing_hellshelf", NETHER_BRICKS));
        // No infused_hellshelf side texture — Zenith aliases it to the base hellshelf face.
        map.put(MeridianShelves.INFUSED_HELLSHELF, column("hellshelf", NETHER_BRICKS));
        // Ocean
        map.put(MeridianShelves.SEASHELF, column("seashelf", PRISMARINE_BRICKS));
        map.put(MeridianShelves.HEART_SEASHELF, column("heart_seashelf", PRISMARINE_BRICKS));
        map.put(MeridianShelves.CRYSTAL_SEASHELF, column("crystal_seashelf", PRISMARINE_BRICKS));
        // No infused_seashelf side texture — Zenith aliases it to the base seashelf face.
        map.put(MeridianShelves.INFUSED_SEASHELF, column("seashelf", PRISMARINE_BRICKS));
        // End
        map.put(MeridianShelves.ENDSHELF, column("endshelf", END_STONE_BRICKS));
        map.put(MeridianShelves.PEARL_ENDSHELF, column("pearl_endshelf", END_STONE_BRICKS));
        map.put(MeridianShelves.DRACONIC_ENDSHELF, column("draconic_endshelf", END_STONE_BRICKS));
        // Deep
        map.put(MeridianShelves.DEEPSHELF, column("deepshelf", CRACKED_DEEPSLATE_TILES));
        // No dormant_deepshelf side texture — Zenith aliases it to the base deepshelf face.
        map.put(MeridianShelves.DORMANT_DEEPSHELF, column("deepshelf", CRACKED_DEEPSLATE_TILES));
        map.put(MeridianShelves.ECHOING_DEEPSHELF, column("echoing_deepshelf", CRACKED_DEEPSLATE_TILES));
        map.put(MeridianShelves.SOUL_TOUCHED_DEEPSHELF, column("soul_touched_deepshelf", CRACKED_DEEPSLATE_TILES));
        // Sculk-tier (reanimated bookshelf subtype, shared end texture)
        map.put(MeridianShelves.ECHOING_SCULKSHELF, column("echoing_sculkshelf", fizzleBlock("sculkshelf_top")));
        map.put(MeridianShelves.SOUL_TOUCHED_SCULKSHELF, column("soul_touched_sculkshelf", fizzleBlock("sculkshelf_top")));
        // Utility — clue shelves
        map.put(MeridianShelves.SIGHTSHELF, column(fizzleBlock("sight_side"), fizzleBlock("sight_top")));
        map.put(MeridianShelves.SIGHTSHELF_T2, column("sightshelf_t2", fizzleBlock("sightshelf_t2_top")));
        // Utility — rectification shelves
        map.put(MeridianShelves.RECTIFIER, column("rectifier", PRISMARINE_BRICKS));
        map.put(MeridianShelves.RECTIFIER_T2, column("rectifier_t2", fizzleBlock("rectifier_t2_top")));
        map.put(MeridianShelves.RECTIFIER_T3, column("rectifier_t3", PURPUR_BLOCK));
        return map;
    }

    private static ColumnTextures column(String sideName, ResourceLocation end) {
        return column(fizzleBlock(sideName), end);
    }

    private static ColumnTextures column(ResourceLocation side, ResourceLocation end) {
        return new ColumnTextures(side, end);
    }

    private static ResourceLocation fizzleBlock(String name) {
        return Meridian.id("block/" + name);
    }

    private static ResourceLocation vanillaBlock(String name) {
        return ResourceLocation.withDefaultNamespace("block/" + name);
    }

    /** Side+end texture pair for a {@code cube_column} shelf model. */
    public record ColumnTextures(ResourceLocation side, ResourceLocation end) {
    }
}
